# Generated by Django 5.2.17 on 2026-08-19 16:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Short welcome copy shown above the workshop card.')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkshopPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('workshop_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(default='Cafe Orelo', max_length=120)),
                ('chef_name', models.CharField(default='Chef Aanchal Wadhwa', max_length=120)),
                ('workshop_subtitle', models.CharField(default='Eggless Tiramisu Making Workshop', help_text='Shown on the page and in WhatsApp messages.', max_length=160)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=Decimal('1499.00'), max_digits=8)),
                ('max_seats_per_booking', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Optional extra details under the event facts.')),
                ('form_note', models.TextField(default='After submitting this form, you will receive your secure payment link. Your seat will be confirmed only after successful payment.')),
                ('group_invite_link', models.URLField(blank=True, help_text='WhatsApp group invite. Sent only after payment — never force-added.')),
                ('payment_description', models.CharField(default='Cafe Orelo - Tiramisu Making Workshop', max_length=180)),
                ('reference_prefix', models.CharField(default='TIRAMISU', max_length=24)),
                ('confirmation_template', models.TextField(default='🎉 Registration Confirmed!\n\nHi {{name}} 👋\n\nYour registration for the Eggless Tiramisu Making Workshop at Cafe Orelo is confirmed! 🍰\n\n📅 {{date}}\n⏰ {{time}}\n📍 {{venue}}\n👩\u200d🍳 {{chef}}\n\n💳 Payment: ₹{{amount}} — PAID\n\n👥 Join the workshop WhatsApp group:\n{{group_invite_link}}\n\nWe’ll share all workshop updates and important details in the group.\n\nSee you at Cafe Orelo! 🤎', help_text='Placeholders: {{name}}, {{group_invite_link}}, {{amount}}, {{date}}, {{time}}, {{venue}}, {{chef}}')),
                ('reminder_template', models.TextField(default="🍰 Your Tiramisu Workshop is tomorrow!\n\nWe're excited to see you at Cafe Orelo tomorrow from 3–5 PM.\n\nPlease arrive 10 minutes early.\n\nSee you tomorrow! 🤎")),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=120)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_link', models.URLField(blank=True)),
                ('payment_link_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('payment_id', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PAYMENT_PENDING', max_length=24)),
                ('group_invite_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('raw_webhook', models.JSONField(blank=True, null=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshop.workshoppage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
