# Generated by Django 5.2.17 on 2026-08-19 18:15

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshoppage',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='registration',
            name='email_invite_sent',
            field=models.BooleanField(default=False, verbose_name='Email invite sent'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='email_body',
            field=models.TextField(default='Hi {{name}},\n\nYour payment is confirmed for {{event}}.\n\n📅 {{date}}\n⏰ {{time}}\n📍 {{venue}}\n👩\u200d🍳 {{chef}}\n\nJoin the WhatsApp group for this workshop (the same invite we send on WhatsApp):\n{{group_invite_link}}\n\nReference: {{reference}}\nSeats: {{seats}}\nAmount paid: ₹{{amount}}\n\nSee you at {{venue}}!\nCafe Orelo\n', help_text='Sent after payment with the WhatsApp group invite. Placeholders: {{name}}, {{event}}, {{date}}, {{time}}, {{venue}}, {{chef}}, {{group_invite_link}}, {{invite_link}}, {{amount}}, {{reference}}, {{seats}}', verbose_name='Email sent after payment'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='email_subject',
            field=models.CharField(default='You’re confirmed for {{event}} at Cafe Orelo', help_text='Same placeholders as the email body.', max_length=180, verbose_name='Email subject after payment'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='enquiry_whatsapp',
            field=models.CharField(blank=True, default='7709818290', help_text='10-digit Indian number shown on the flyer. Leave blank to hide the enquiry link.', max_length=16, verbose_name='Enquiry WhatsApp number'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='gold_banner',
            field=models.CharField(default='Eggless tiramisu making', max_length=80, verbose_name='Gold banner line'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='hero_kicker',
            field=models.CharField(default='Making Workshop', max_length=80, verbose_name='Small title under the big word'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='hero_title',
            field=models.CharField(default='Tiramisu', max_length=40, verbose_name='Big title on the flyer'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='limited_seats_line',
            field=models.CharField(default='Limited seats. Book your spot now!', max_length=120, verbose_name='Limited seats line'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='seat_capacity',
            field=models.PositiveSmallIntegerField(default=20, help_text='Sold out when paid bookings reach this number. Pending payments do not hold a seat.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Total seats for this event'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='tagline',
            field=models.CharField(default='Learn. Create. Indulge.', max_length=80, verbose_name='Script line at the top'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='take_home_intro',
            field=models.CharField(default='What you will take home?', max_length=80, verbose_name='Take-home heading'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='take_home_list',
            field=models.TextField(default='Your own handmade eggless tiramisu\nDetailed recipe sheet\nHands-on learning & techniques\nComplimentary beverage\nA fun baking experience with fellow dessert lovers', help_text='One item per line. These show on the public flyer.', verbose_name='What guests take home'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short welcome copy shown above the event cards when more than one workshop is live.', verbose_name='Welcome line'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='group_invite_sent',
            field=models.BooleanField(default=False, verbose_name='WhatsApp invite sent'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshop.workshoppage', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='chef_name',
            field=models.CharField(default='Aanchal Wadhwa', max_length=120, verbose_name='Chef name'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='confirmation_template',
            field=models.TextField(default='🎉 Registration Confirmed!\n\nHi {{name}} 👋\n\nYour registration for {{event}} at {{venue}} is confirmed! 🍰\n\n📅 {{date}}\n⏰ {{time}}\n📍 {{venue}}\n👩\u200d🍳 {{chef}}\n\n💳 Payment: ₹{{amount}} — PAID\n\n👥 Join the workshop WhatsApp group:\n{{group_invite_link}}\n\nWe’ll share all workshop updates and important details in the group.\n\nSee you at {{venue}}! 🤎', help_text='Placeholders: {{name}}, {{event}}, {{group_invite_link}}, {{amount}}, {{date}}, {{time}}, {{venue}}, {{chef}}, {{reference}}, {{seats}}', verbose_name='WhatsApp message after payment'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional extra details under the event facts.', verbose_name='Extra details'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='form_note',
            field=models.TextField(default='After submitting this form, you will receive your secure payment link. Your seat will be confirmed only after successful payment.', verbose_name='Note under the booking form'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='group_invite_link',
            field=models.URLField(blank=True, help_text='Paste the group invite. Sent only after payment — we never force-add anyone.', verbose_name='WhatsApp group invite link'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero image'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='max_seats_per_booking',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Max seats one guest can book'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='payment_description',
            field=models.CharField(default='Cafe Orelo workshop', help_text='Shown on the unique Razorpay Payment Link. The booking reference is added automatically.', max_length=180, verbose_name='Payment link description'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=Decimal('1499.00'), max_digits=8, verbose_name='Price per seat (₹)'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='reference_prefix',
            field=models.CharField(default='ORELO', help_text='Used in payment references, e.g. ORELO-20260823-001.', max_length=24, verbose_name='Booking reference prefix'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='reminder_template',
            field=models.TextField(default="🍰 {{event}} is tomorrow!\n\nWe're excited to see you at {{venue}} tomorrow from {{time}}.\n\nPlease arrive 10 minutes early.\n\nSee you tomorrow! 🤎", help_text='Same placeholders as the confirmation message.', verbose_name='WhatsApp reminder (day before)'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='venue',
            field=models.CharField(default='Cafe Orelo', max_length=120, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='workshop_date',
            field=models.DateField(verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='workshop_subtitle',
            field=models.CharField(default='Eggless Tiramisu Making Workshop', help_text='Shown on the page and in WhatsApp / email. Use {{event}} in the templates below.', max_length=160, verbose_name='Event name (on the page and in messages)'),
        ),
    ]
