# Generated by Django 5.2.17 on 2026-08-20 10:32

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from decimal import Decimal
from django.db import migrations, models


TIRAMISU_PAYMENT_LINK = "https://rzp.io/rzp/CW6o0Mec"


def seed_tiramisu_packages(apps, schema_editor):
    WorkshopPage = apps.get_model("workshop", "WorkshopPage")
    WorkshopPackage = apps.get_model("workshop", "WorkshopPackage")
    page = WorkshopPage.objects.filter(slug="tiramisu-workshop").first()
    if page is None:
        page = WorkshopPage.objects.filter(pk=4).first()
    if page is None or WorkshopPackage.objects.filter(page_id=page.pk).exists():
        return
    seeds = (
        {
            "name": "1 Seat",
            "seats": 1,
            "price": Decimal("1499.00"),
            "payment_link": TIRAMISU_PAYMENT_LINK,
            "note": "",
            "sort_order": 0,
        },
        {
            "name": "2 Seats",
            "seats": 2,
            "price": Decimal("2998.00"),
            "payment_link": "",
            "note": "Paste the 2-seat Razorpay link when you have it.",
            "sort_order": 1,
        },
        {
            "name": "3 Seats",
            "seats": 3,
            "price": Decimal("4497.00"),
            "payment_link": "",
            "note": "Paste the 3-seat Razorpay link when you have it.",
            "sort_order": 2,
        },
    )
    for data in seeds:
        WorkshopPackage.objects.create(page_id=page.pk, **data)


def unseed_tiramisu_packages(apps, schema_editor):
    WorkshopPage = apps.get_model("workshop", "WorkshopPage")
    WorkshopPackage = apps.get_model("workshop", "WorkshopPackage")
    page = WorkshopPage.objects.filter(slug="tiramisu-workshop").first()
    if page is None:
        page = WorkshopPage.objects.filter(pk=4).first()
    if page is None:
        return
    WorkshopPackage.objects.filter(page_id=page.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_workshoppage_payment_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='package_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Package name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='seats',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='max_seats_per_booking',
            field=models.PositiveSmallIntegerField(default=3, help_text='Used only when this event has no packages (fallback seat picker).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Max seats one guest can book'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='payment_link_url',
            field=models.URLField(blank=True, help_text='Used only if this event has no packages. Shared rzp.io URL priced for one seat; multi-seat guests pay that same link once per seat. Prefer adding Packages instead.', verbose_name='Fallback Razorpay payment link (per seat)'),
        ),
        migrations.CreateModel(
            name='WorkshopPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='e.g. “1 Seat”, “2 Seats”, “Couple”.', max_length=80, verbose_name='Package name')),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Seats included')),
                ('price', models.DecimalField(decimal_places=2, help_text='INR, rupees. Shown as ₹ on the public form.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Price (₹)')),
                ('payment_link', models.URLField(blank=True, help_text='The rzp.io or Razorpay Payment Link URL for this package. Leave empty to hide this option on the public form.', verbose_name='Razorpay payment link')),
                ('note', models.CharField(blank=True, help_text='Optional. Shown next to the package on the public form.', max_length=160, verbose_name='Short note')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='workshop.workshoppage')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='workshop.workshoppackage', verbose_name='Package'),
        ),
        migrations.RunPython(seed_tiramisu_packages, unseed_tiramisu_packages),
    ]
