# Generated by Django 5.2.17 on 2026-08-20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_workshop_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshoppage",
            name="reminder_hours_before",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Send the reminder this many hours before the event start (email + WhatsApp). Default 24. Vercel cron runs daily at 15:00 IST.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(168),
                ],
                verbose_name="Reminder hours before start",
            ),
        ),
        migrations.AddField(
            model_name="workshoppage",
            name="reminder_email_subject",
            field=models.CharField(
                default="Reminder: {{event}} at Cafe Orelo",
                help_text="Same placeholders as the reminder message.",
                max_length=180,
                verbose_name="Reminder email subject",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Reminder sent"),
        ),
        migrations.AlterField(
            model_name="workshoppage",
            name="email_body",
            field=models.TextField(
                default="Hi {{name}},\n\nYour payment is confirmed for {{event}}.\n\n📅 {{date}}\n⏰ {{time}}\n📍 {{venue}}\n👩\u200d🍳 {{chef}}\n🎟️ Package: {{package}}\n\nJoin the WhatsApp group for this workshop (the same invite we send on WhatsApp):\n{{group_invite_link}}\n\nReference: {{reference}}\nSeats: {{seats}}\nAmount paid: ₹{{amount}}\n\nSee you at {{venue}}!\nCafe Orelo\n",
                help_text="Sent after payment with the WhatsApp group invite. Placeholders: {{name}}, {{event}}, {{date}}, {{time}}, {{venue}}, {{chef}}, {{group_invite_link}}, {{invite_link}}, {{amount}}, {{reference}}, {{seats}}, {{package}}",
                verbose_name="Email sent after payment",
            ),
        ),
        migrations.AlterField(
            model_name="workshoppage",
            name="reminder_template",
            field=models.TextField(
                default="🍰 {{event}} is tomorrow!\n\nWe're excited to see you at {{venue}} tomorrow from {{time}}.\n\nPlease arrive 10 minutes early.\n\nSee you tomorrow! 🤎",
                help_text="Used for both WhatsApp and the reminder email body. Same placeholders as the confirmation message, plus {{package}}.",
                verbose_name="Reminder message (WhatsApp + email)",
            ),
        ),
    ]
